/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LogIcon: typeof import('./src/components/LogIcon.vue')['default']
    LogViewer: typeof import('./src/components/LogViewer.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    WelcomePage: typeof import('./src/components/WelcomePage.vue')['default']
  }
}
