// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentFile(arg1) {
  return window['go']['main']['App']['AddRecentFile'](arg1);
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function ExportLogLines(arg1, arg2) {
  return window['go']['main']['App']['ExportLogLines'](arg1, arg2);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetFilesInDirectory(arg1) {
  return window['go']['main']['App']['GetFilesInDirectory'](arg1);
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleFileDrop(arg1) {
  return window['go']['main']['App']['HandleFileDrop'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadLogFile(arg1) {
  return window['go']['main']['App']['ReadLogFile'](arg1);
}

export function RemoveRecentFile(arg1) {
  return window['go']['main']['App']['RemoveRecentFile'](arg1);
}

export function SaveFileDialog() {
  return window['go']['main']['App']['SaveFileDialog']();
}

export function SearchInFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchInFile'](arg1, arg2, arg3);
}

export function SearchInFileWithRegex(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchInFileWithRegex'](arg1, arg2, arg3);
}
