// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddRecentFile(arg1:string):Promise<void>;

export function ClearRecentFiles():Promise<void>;

export function ExportLogLines(arg1:Array<string>,arg2:string):Promise<void>;

export function GetFileInfo(arg1:string):Promise<models.LogFile>;

export function GetFilesInDirectory(arg1:string):Promise<Array<models.LogFile>>;

export function GetRecentFiles():Promise<Array<models.LogFile>>;

export function GetSystemInfo():Promise<models.SystemInfo>;

export function Greet(arg1:string):Promise<string>;

export function HandleFileDrop(arg1:string):Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadLogFile(arg1:string):Promise<models.LogContent>;

export function RemoveRecentFile(arg1:string):Promise<void>;

export function SaveFileDialog():Promise<string>;

export function SearchInFile(arg1:string,arg2:string,arg3:boolean):Promise<Array<models.SearchResult>>;

export function SearchInFileWithRegex(arg1:string,arg2:string,arg3:boolean):Promise<Array<models.SearchResult>>;
